GET http://localhost:5206/games

###
GET http://localhost:5206/games/d4d78f1f-980b-4c78-83f3-9cb92599521a

###
POST http://localhost:5206/games
Content-Type: application/json

{
    "name": "Call of Duty",
    "genre": {
        "id": "cb4fa849-074b-4d58-ad10-a0bc40cbf097",
        "name": "Action"
    },
    "price": 99.99,
    "releaseDate": "2027-07-26",
    "description": "this is a good game."
}